### ISSUE TITLE
Fleet

### ISSUE THREAD

**Issue by farnasirim** [cafebazaar/blacksmith-kubernetes#1]
Why do we need [this](https://github.com/cafebazaar/blacksmith-kubernetes/blob/61d2b739e13b89f61cacf5e5eb526652e6b72387/blacksmith/templates/common-units.yaml#L4)?

**Comment by arastu** [comment]
Kubernetes is composed of multiple services such as the kubelet server, API server, scheduler, and replication controller and they all run as Fleet units.

**Comment by remohammadi** [comment]
@arastu Are they? I think the current config doesn't need fleet, and so we can disable it 😸

**Comment by arastu** [comment]
@remohammadi I'm not sure :) but I guess this is true in the earlier version of kubernetes.

as regards fleet is used for orchestration of critical system service using systemd, at the current state we don't need fleet at all?

**Comment by farnasirim** [comment]
we don't need it AFAIK and we can get rid of the line starting it for good.
