### ISSUE TITLE
Interface names

### ISSUE THREAD

**Issue by farnasirim** [cafebazaar/blacksmith-kubernetes#4]
In the current state, the name of the machine network interfaces are needed to be known for [this](https://github.com/cafebazaar/blacksmith-kubernetes/blob/master/blacksmith/templates/bootstrapper2.yaml#L19) to work, and what makes things even worse is that they all need to be the same since there is only one value supplied to the templates for this purpose. 

The workers have to obey such naming convention too (see [this](https://github.com/cafebazaar/blacksmith-kubernetes/blob/master/blacksmith/templates/worker.yaml#L20)). It is highly unlikely that the internal interface name of a new machine that is being added as a worker to the cluster is equal to the name of the internal interface of the previous (and possibly from a different vendor) workers‌ (and even the masters).

And even with all that fixed, figuring out the interface names and which name corresponds to which physical interface is a task which most probably will need physical human interaction with the machine.

The name of the interface is currently needed for configuring bootstrappers and workers networks and running blacksmith on bootsrappers‌. (Am‌ I missing anything here?)

We most probably want bootstrappers to bring up blacksmith on their internal interface (this definition of "internal interface" goes the same way for workers too) i.e. the one from which they received PXE boot configurations, but the interface names are not needed to be known [the first time they boot](https://github.com/cafebazaar/blacksmith-kubernetes/blob/master/blacksmith/config/cloudconfig/new.yaml).

We can inject a script which sends the "internal" interface name of the newly booted machine to the bootstrappers, and with [this](https://github.com/cafebazaar/blacksmith/issues/29) fixed, the machines can put their internal interface name in masters etcd themselves. The templates/blacksmith run scripts can then be cooked based on these values (in the latter case we can even query etcd directly) and with a little luck (?)  we probably won't need to change anything else in [blacksmith](https://github.com/cafebazaar/blacksmith).

@remohammadi your thoughts on this?

**Comment by remohammadi** [comment]
On the matter of internal network, I'm working to empower the `dhcp` package, to be more flexible, and removes the need for a custom configuration in the cloud-config.

And for the public network, we can use _cloud variables_ (new name for flags!) to set the interface name. @givia is working on [Global flags](https://github.com/cafebazaar/blacksmith/issues/32), so we'll be able to set a default for the public interface name, and set the name only for the different machines

**Comment by farnasirim** [comment]
Very nice. And how about bootstrappers' internal interface names since they have to run blacksmith?

**Comment by remohammadi** [comment]
For that, we still need [that](https://github.com/cafebazaar/blacksmith/issues/29)!

**Comment by arastu** [comment]
keep calm and do not kill the intern 😆 
[this](https://github.com/cafebazaar/blacksmith/issues/29) is mostly finished, and completely done tomorrow morning. 🚀

**Comment by farnasirim** [comment]
@remohammadi how about selecting the interface on which blacksmith runs based on IP instead of name in the first place?

**Comment by remohammadi** [comment]
We're going to resolve this issue for workers by passing [static route config through DHCP](https://github.com/cafebazaar/blacksmith/issues/43), and so removing the entire [internal network configuration for workers](https://github.com/cafebazaar/blacksmith-kubernetes/blob/5272319fc80482399e8c146a2f6282f1134c7cd3/blacksmith/templates/worker.yaml#L16-L34).

And we're going to keep Bootstrappers' configuration dependent on the interface name for now!
